# Generated by Django 3.1.3 on 2021-01-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '类别'},
        ),
        migrations.AlterModelOptions(
            name='equipmentsource',
            options={'verbose_name_plural': '设备来源'},
        ),
        migrations.AlterModelOptions(
            name='equipmentstate',
            options={'verbose_name_plural': '设备状态'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name_plural': '设备标签信息表'},
        ),
        migrations.AlterModelOptions(
            name='operationrecord',
            options={'verbose_name_plural': '设备运行记录信息表'},
        ),
        migrations.AlterModelOptions(
            name='usagestate',
            options={'verbose_name_plural': '使用状态'},
        ),
        migrations.AlterField(
            model_name='label',
            name='QR_code',
            field=models.ImageField(blank=True, db_column='二维码', null=True, upload_to='QR_code/%Y/%m/%d/', verbose_name='二维码'),
        ),
        migrations.AlterField(
            model_name='label',
            name='bar_code',
            field=models.ImageField(blank=True, db_column='条形码', null=True, upload_to='bar_code/%Y/%m/%d/', verbose_name='条形码'),
        ),
    ]
