# Generated by Django 3.1.3 on 2021-01-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0002_auto_20210111_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, db_column='类别', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_source',
            field=models.ForeignKey(blank=True, db_column='设备来源', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipmentsource', verbose_name='设备来源'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_state',
            field=models.ForeignKey(blank=True, db_column='设备状态', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipmentstate', verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='usage_state',
            field=models.ForeignKey(blank=True, db_column='使用状态', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.usagestate', verbose_name='使用状态'),
        ),
    ]
