# Generated by Django 3.1.3 on 2021-01-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0003_auto_20210111_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('-creation_time',), 'verbose_name_plural': '设备基本信息表'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='remark',
            field=models.CharField(blank=True, db_column='备注', max_length=256, null=True, verbose_name='备注'),
        ),
    ]
