# Generated by Django 3.1.3 on 2021-01-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0004_auto_20210113_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '4类别'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('-creation_time',), 'verbose_name_plural': '1设备基本信息表'},
        ),
        migrations.AlterModelOptions(
            name='equipmentsource',
            options={'verbose_name_plural': '4设备来源'},
        ),
        migrations.AlterModelOptions(
            name='equipmentstate',
            options={'verbose_name_plural': '4设备状态'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name_plural': '2设备标签信息表'},
        ),
        migrations.AlterModelOptions(
            name='operationrecord',
            options={'verbose_name_plural': '3设备运行记录信息表'},
        ),
        migrations.AlterModelOptions(
            name='usagestate',
            options={'verbose_name_plural': '4使用状态'},
        ),
    ]
