# Generated by Django 3.1.3 on 2021-01-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0006_auto_20210125_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_id',
            field=models.IntegerField(blank=True, db_column='父id', max_length=32, null=True, verbose_name='父id'),
        ),
    ]
