# Generated by Django 3.1.3 on 2021-01-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0007_auto_20210125_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='父id', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.department', verbose_name='父id'),
        ),
    ]
