# Generated by Django 3.1.3 on 2021-01-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0008_auto_20210125_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_place_name', models.CharField(db_column='存放位置', max_length=64, verbose_name='存放位置')),
                ('parent_id', models.ForeignKey(blank=True, db_column='父id', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.storageplace', verbose_name='父id')),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='storage_place',
            field=models.ForeignKey(blank=True, db_column='存放位置', null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.storageplace', verbose_name='存放位置'),
        ),
    ]
