# Generated by Django 3.1.3 on 2021-01-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0009_auto_20210125_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='parent_number',
            field=models.CharField(blank=True, db_column='父编号', max_length=64, null=True, verbose_name='父编号'),
        ),
    ]
