# Generated by Django 3.1.3 on 2021-01-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0010_equipment_parent_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='parent_number',
        ),
    ]
