# Generated by Django 3.1.3 on 2021-02-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0011_remove_equipment_parent_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='relevant_document',
        ),
        migrations.CreateModel(
            name='EquipmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant_document', models.FileField(blank=True, db_column='相关文件', null=True, upload_to='equipment_relevant_document', verbose_name='相关文件')),
                ('equipment', models.ForeignKey(db_column='设备编号', on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipment', verbose_name='设备编号')),
            ],
        ),
    ]
