# Generated by Django 3.1.3 on 2021-02-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0012_auto_20210205_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentfile',
            options={'verbose_name_plural': '1设备文件'},
        ),
        migrations.AlterModelTable(
            name='equipmentfile',
            table='设备文件',
        ),
    ]
