# Generated by Django 3.1.3 on 2021-02-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0013_auto_20210205_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '14部门'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('-creation_time',), 'verbose_name_plural': '11设备基本信息表'},
        ),
        migrations.AlterModelOptions(
            name='equipmentfile',
            options={'verbose_name_plural': '12设备文件'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name_plural': '15设备标签信息表'},
        ),
        migrations.AlterModelOptions(
            name='operationrecord',
            options={'verbose_name_plural': '16设备运行记录信息表'},
        ),
        migrations.AlterModelOptions(
            name='storageplace',
            options={'verbose_name_plural': '13存放位置'},
        ),
        migrations.AlterModelTable(
            name='department',
            table='14部门',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='11设备基本信息表',
        ),
        migrations.AlterModelTable(
            name='equipmentfile',
            table='12设备文件',
        ),
        migrations.AlterModelTable(
            name='label',
            table='15设备标签信息表',
        ),
        migrations.AlterModelTable(
            name='operationrecord',
            table='16设备运行记录信息表',
        ),
        migrations.AlterModelTable(
            name='storageplace',
            table='13存放位置',
        ),
    ]
