# Generated by Django 3.1.3 on 2021-02-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0014_auto_20210205_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '17类别'},
        ),
        migrations.AlterModelOptions(
            name='equipmentsource',
            options={'verbose_name_plural': '19设备来源'},
        ),
        migrations.AlterModelOptions(
            name='equipmentstate',
            options={'verbose_name_plural': '18设备状态'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='17类别',
        ),
        migrations.AlterModelTable(
            name='equipmentsource',
            table='19设备来源',
        ),
        migrations.AlterModelTable(
            name='equipmentstate',
            table='18设备状态',
        ),
    ]
