# Generated by Django 3.1.3 on 2021-02-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0015_auto_20210205_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagestate',
            options={'verbose_name_plural': '110使用状态'},
        ),
        migrations.AlterModelTable(
            name='usagestate',
            table='110使用状态',
        ),
    ]
