# Generated by Django 3.1.3 on 2021-02-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0016_auto_20210205_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '05类别'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '03部门'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ('-creation_time',), 'verbose_name_plural': '00设备基本信息表'},
        ),
        migrations.AlterModelOptions(
            name='equipmentfile',
            options={'verbose_name_plural': '01设备文件'},
        ),
        migrations.AlterModelOptions(
            name='equipmentsource',
            options={'verbose_name_plural': '07设备来源'},
        ),
        migrations.AlterModelOptions(
            name='equipmentstate',
            options={'verbose_name_plural': '06设备状态'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name_plural': '08设备标签信息表'},
        ),
        migrations.AlterModelOptions(
            name='operationrecord',
            options={'verbose_name_plural': '09设备运行记录信息表'},
        ),
        migrations.AlterModelOptions(
            name='storageplace',
            options={'verbose_name_plural': '02存放位置'},
        ),
        migrations.AlterModelOptions(
            name='usagestate',
            options={'verbose_name_plural': '04使用状态'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='05类别',
        ),
        migrations.AlterModelTable(
            name='department',
            table='03部门',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='00设备基本信息表',
        ),
        migrations.AlterModelTable(
            name='equipmentfile',
            table='01设备文件',
        ),
        migrations.AlterModelTable(
            name='equipmentsource',
            table='07设备来源',
        ),
        migrations.AlterModelTable(
            name='equipmentstate',
            table='06设备状态',
        ),
        migrations.AlterModelTable(
            name='label',
            table='08设备标签信息表',
        ),
        migrations.AlterModelTable(
            name='operationrecord',
            table='09设备运行记录信息表',
        ),
        migrations.AlterModelTable(
            name='storageplace',
            table='02存放位置',
        ),
        migrations.AlterModelTable(
            name='usagestate',
            table='04使用状态',
        ),
    ]
