# Generated by Django 3.1.3 on 2021-01-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionproject',
            name='reference_inspection_period',
        ),
        migrations.AddField(
            model_name='inspectionstandard',
            name='reference_inspection_period',
            field=models.CharField(blank=True, db_column='参考点检周期', max_length=32, null=True, verbose_name='参考点检周期'),
        ),
    ]
