# Generated by Django 3.1.3 on 2021-01-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0002_auto_20210129_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('inspection_plan_number', models.CharField(db_column='点检计划编号', max_length=64, primary_key=True, serialize=False, verbose_name='点检计划编号')),
                ('inspection_plan_name', models.CharField(db_column='点检计划名称', max_length=64, verbose_name='点检计划名称')),
                ('creator', models.CharField(blank=True, db_column='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('principal', models.CharField(blank=True, db_column='负责人', max_length=64, null=True, verbose_name='负责人')),
                ('start_time', models.DateField(blank=True, db_column='开始时间', null=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, db_column='结束时间', null=True, verbose_name='结束时间')),
                ('plan_status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], db_column='计划状态', default=0, verbose_name='计划状态')),
                ('inspection_period', models.CharField(db_column='点检周期(天)', max_length=32, verbose_name='点检周期(天)')),
                ('remark', models.CharField(blank=True, db_column='备注', max_length=512, null=True, verbose_name='备注')),
                ('inspection_standard', models.ManyToManyField(to='inspection_management.InspectionStandard', verbose_name='点检标准')),
            ],
            options={
                'verbose_name_plural': '点检计划',
                'db_table': '点检计划',
            },
        ),
    ]
