# Generated by Django 3.1.3 on 2021-01-29 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0003_inspectionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('inspection_task_number', models.CharField(db_column='点检任务编号', max_length=64, primary_key=True, serialize=False, verbose_name='点检任务编号')),
                ('task_start_time', models.DateTimeField(verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(verbose_name='任务结束时间')),
                ('task_status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成'), (3, '未完成')], default=0)),
                ('belong_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection_management.inspectionplan', verbose_name='所属计划')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_value', models.CharField(blank=True, db_column='巡检值', max_length=64, null=True, verbose_name='巡检值')),
                ('is_unusual', models.IntegerField(choices=[(0, '否'), (1, '是')], db_column='是否异常', default=0, verbose_name='是否异常')),
                ('inspection_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection_management.inspectionproject', verbose_name='点检项目')),
                ('inspection_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection_management.inspectiontask', verbose_name='点检任务')),
            ],
        ),
    ]
