# Generated by Django 3.1.3 on 2021-01-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0005_auto_20210129_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionstandard',
            options={'verbose_name_plural': '点巡检标准'},
        ),
        migrations.AlterField(
            model_name='inspectionstandard',
            name='inspection_standard_name',
            field=models.CharField(db_column='点巡检标准名称', max_length=64, verbose_name='点巡检标准名称'),
        ),
        migrations.AlterField(
            model_name='inspectionstandard',
            name='inspection_standard_number',
            field=models.CharField(db_column='点巡检标准编号', max_length=64, primary_key=True, serialize=False, verbose_name='点巡检标准编号'),
        ),
        migrations.AlterField(
            model_name='inspectionstandard',
            name='reference_inspection_period',
            field=models.CharField(blank=True, db_column='参考点巡检周期', max_length=32, null=True, verbose_name='参考点巡检周期'),
        ),
        migrations.AlterModelTable(
            name='inspectionstandard',
            table='点巡检标准',
        ),
    ]
