# Generated by Django 3.1.3 on 2021-01-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0006_auto_20210129_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontask',
            name='inspected_number',
            field=models.IntegerField(blank=True, db_column='已检数', null=True, verbose_name='已检数'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='inspection_project_count',
            field=models.IntegerField(blank=True, db_column='巡检项个数', null=True, verbose_name='巡检项个数'),
        ),
    ]
