# Generated by Django 3.1.3 on 2021-01-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0009_inspectiontask_inspection_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionresult',
            options={},
        ),
        migrations.AlterModelTable(
            name='inspectionresult',
            table=None,
        ),
    ]
