# Generated by Django 3.1.3 on 2021-01-31 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0012_auto_20210131_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionplan',
            options={'verbose_name_plural': '3点检计划'},
        ),
        migrations.AlterModelOptions(
            name='inspectionproject',
            options={'verbose_name_plural': '1点检项目'},
        ),
        migrations.AlterModelOptions(
            name='inspectionstandard',
            options={'verbose_name_plural': '2点巡检标准'},
        ),
        migrations.AlterModelTable(
            name='inspectionplan',
            table='3点检计划',
        ),
        migrations.AlterModelTable(
            name='inspectionproject',
            table='1点检项目',
        ),
        migrations.AlterModelTable(
            name='inspectionstandard',
            table='2点巡检标准',
        ),
    ]
