# Generated by Django 3.1.3 on 2021-01-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0013_auto_20210131_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectiontask',
            options={'verbose_name_plural': '4点检任务'},
        ),
        migrations.AlterModelTable(
            name='inspectiontask',
            table='4点检任务',
        ),
    ]
