# Generated by Django 3.1.3 on 2021-01-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0014_auto_20210131_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionresult',
            options={'verbose_name_plural': '5点检项目_点检任务_点检结果'},
        ),
        migrations.AlterModelTable(
            name='inspectionresult',
            table='5点检项目_点检任务_点检结果',
        ),
    ]
