# Generated by Django 3.1.3 on 2021-01-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0017_auto_20210131_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionplan',
            name='inspection_standard',
        ),
    ]
