# Generated by Django 3.1.3 on 2021-01-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0018_remove_inspectionplan_inspection_standard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectiontask',
            name='inspection_projects',
        ),
        migrations.AddField(
            model_name='inspectionplan',
            name='inspection_standard',
            field=models.ManyToManyField(to='inspection_management.InspectionStandard', verbose_name='点检标准'),
        ),
    ]
