# Generated by Django 3.1.3 on 2021-02-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0022_auto_20210203_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionplan',
            options={'verbose_name_plural': '03点检计划'},
        ),
        migrations.AlterModelOptions(
            name='inspectionproject',
            options={'verbose_name_plural': '01点检项目'},
        ),
        migrations.AlterModelOptions(
            name='inspectionresult',
            options={'verbose_name_plural': '05点检项目_点检任务_点检结果'},
        ),
        migrations.AlterModelOptions(
            name='inspectionstandard',
            options={'verbose_name_plural': '02点巡检标准'},
        ),
        migrations.AlterModelOptions(
            name='inspectiontask',
            options={'verbose_name_plural': '04点检任务'},
        ),
        migrations.AlterModelTable(
            name='inspectionplan',
            table='03点检计划',
        ),
        migrations.AlterModelTable(
            name='inspectionproject',
            table='01点检项目',
        ),
        migrations.AlterModelTable(
            name='inspectionresult',
            table='05点检项目_点检任务_点检结果',
        ),
        migrations.AlterModelTable(
            name='inspectionstandard',
            table='02点巡检标准',
        ),
        migrations.AlterModelTable(
            name='inspectiontask',
            table='04点检任务',
        ),
    ]
