# Generated by Django 3.1.3 on 2021-02-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_management', '0023_auto_20210205_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionplan',
            options={'verbose_name_plural': '33点检计划'},
        ),
        migrations.AlterModelOptions(
            name='inspectionproject',
            options={'verbose_name_plural': '31点检项目'},
        ),
        migrations.AlterModelOptions(
            name='inspectionresult',
            options={'verbose_name_plural': '35点检项目_点检任务_点检结果'},
        ),
        migrations.AlterModelOptions(
            name='inspectionstandard',
            options={'verbose_name_plural': '32点巡检标准'},
        ),
        migrations.AlterModelOptions(
            name='inspectiontask',
            options={'verbose_name_plural': '34点检任务'},
        ),
        migrations.AlterModelTable(
            name='inspectionplan',
            table='33点检计划',
        ),
        migrations.AlterModelTable(
            name='inspectionproject',
            table='31点检项目',
        ),
        migrations.AlterModelTable(
            name='inspectionresult',
            table='35点检项目_点检任务_点检结果',
        ),
        migrations.AlterModelTable(
            name='inspectionstandard',
            table='32点巡检标准',
        ),
        migrations.AlterModelTable(
            name='inspectiontask',
            table='34点检任务',
        ),
    ]
