# Generated by Django 3.1.3 on 2021-01-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment_management', '0005_auto_20210116_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceInformation',
            fields=[
                ('maintenance_standard_number', models.CharField(db_column='保养信息编号', max_length=64, primary_key=True, serialize=False, verbose_name='保养信息编号')),
                ('maintenance_content', models.TextField(db_column='保养内容', verbose_name='保养内容')),
                ('remark', models.CharField(blank=True, db_column='备注', max_length=512, null=True, verbose_name='备注')),
                ('equipment_number', models.ForeignKey(db_column='设备编号', on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipment', verbose_name='设备编号')),
            ],
            options={
                'verbose_name_plural': '1保养信息',
                'db_table': '保养信息',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('maintenance_plan_number', models.CharField(db_column='保养计划编号', max_length=64, primary_key=True, serialize=False, verbose_name='保养计划编号')),
                ('plan_name', models.CharField(db_column='计划名称', max_length=64, verbose_name='计划名称')),
                ('creator', models.CharField(blank=True, db_column='创建人', max_length=64, null=True, verbose_name='创建人')),
                ('principal', models.CharField(blank=True, db_column='负责人', max_length=64, null=True, verbose_name='负责人')),
                ('acceptor', models.CharField(blank=True, db_column='验收人', max_length=64, null=True, verbose_name='验收人')),
                ('start_time', models.DateField(blank=True, db_column='开始时间', null=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, db_column='结束时间', null=True, verbose_name='结束时间')),
                ('plan_status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], db_column='计划状态', default=0, verbose_name='计划状态')),
                ('remark', models.CharField(blank=True, db_column='备注', max_length=512, null=True, verbose_name='备注')),
                ('maintenance_time_point', models.CharField(blank=True, db_column='保养周期(天)', max_length=128, null=True, verbose_name='保养周期(天)')),
                ('maintenance_information', models.ManyToManyField(to='maintenance_management.MaintenanceInformation', verbose_name='保养信息')),
            ],
            options={
                'verbose_name_plural': '1保养计划',
                'db_table': '保养计划',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('maintenance_type', models.CharField(db_column='保养类型', max_length=32, primary_key=True, serialize=False, verbose_name='保养类型')),
            ],
            options={
                'verbose_name_plural': '1保养类型',
                'db_table': '保养类型',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0)),
                ('task_start_time', models.DateField(verbose_name='任务开始时间')),
                ('task_end_time', models.DateField(verbose_name='任务结束时间')),
                ('acceptance_phase', models.IntegerField(choices=[(0, '未验收'), (1, '验收通过'), (2, '验收不通过')], db_column='验收状态', default=0, verbose_name='验收状态')),
                ('acceptance_descriptions', models.CharField(blank=True, db_column='验收说明', max_length=512, null=True, verbose_name='验收说明')),
                ('belong_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance_management.maintenanceplan', verbose_name='所属计划')),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceinformation',
            name='maintenance_type',
            field=models.ForeignKey(db_column='保养类型', on_delete=django.db.models.deletion.CASCADE, to='maintenance_management.maintenancetype', verbose_name='保养类型'),
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceinformation',
            unique_together={('equipment_number', 'maintenance_type')},
        ),
    ]
