# Generated by Django 3.1.3 on 2021-01-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='maintenance_record',
            field=models.CharField(blank=True, db_column='保养记录', max_length=512, null=True, verbose_name='保养记录'),
        ),
    ]
