# Generated by Django 3.1.3 on 2021-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0011_remove_equipment_parent_number'),
        ('maintenance_management', '0003_auto_20210127_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenanceInformation',
            new_name='MaintenanceStandard',
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='task_end_time',
            field=models.DateTimeField(verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='task_start_time',
            field=models.DateTimeField(verbose_name='任务开始时间'),
        ),
    ]
