# Generated by Django 3.1.3 on 2021-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_management', '0004_auto_20210128_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='task_status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成'), (3, '未完成')], default=0),
        ),
    ]
