# Generated by Django 3.1.3 on 2021-01-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_management', '0005_auto_20210129_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancestandard',
            options={'verbose_name_plural': '1保养标准'},
        ),
        migrations.AlterModelTable(
            name='maintenancestandard',
            table='保养标准',
        ),
    ]
