# Generated by Django 3.1.3 on 2021-02-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_management', '0007_auto_20210205_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'verbose_name_plural': '24保养任务'},
        ),
        migrations.AlterModelTable(
            name='maintenancetask',
            table='24保养任务',
        ),
    ]
